name: Java CI with Maven
# Specified the paths so that the build will only occur when there is a change in the source code i.e. .js file
on:
  push:
    paths:
      - 'NewCodePhillips/src/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
# Specified the various java versions that can be run using matrix and array.
    strategy:
      matrix:
        java-version: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - run: mvn -B install --no-transfer-progress --file pom.xml
